# Generated by Django 4.1.4 on 2022-12-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='apellido',
        ),
    ]
